export const JUMP_SOUND_LIST = [
  ["ui_reaction_kaizen_yeah_c"],
  ["ui_reaction_kaizen_wow_a", "ui_reaction_kaizen_wow_c"],
  ["ui_reaction_kaizen_laugh-d", "ui_reaction_kaizen_laugh_a", "ui_reaction_kaizen_laugh_b", "ui_reaction_kaizen_laugh_c"],
  ["ui_reaction_kaizen_love-it_c"],
  ["ui_reaction_kaizen_brilliant_a", "ui_reaction_kaizen_brilliant_b", "ui_reaction_kaizen_brilliant_c"],
  ["ui_reaction_kaizen_can-t_believe-it_a", "ui_reaction_kaizen_can-t_believe-it_b", "ui_reaction_kaizen_can-t_believe-it_c"],
  ["ui_reaction_kaizen_cool_a", "ui_reaction_kaizen_cool_b", "ui_reaction_kaizen_cool_c"],
  ["ui_reaction_kaizen_excited_a", "ui_reaction_kaizen_excited_b", "ui_reaction_kaizen_excited_c"],
  //END OF COMMON
  ["ui_reaction_kaizen_whee_a", "ui_reaction_kaizen_whee_b", "ui_reaction_kaizen_whee_c"],
  ["ui_reaction_kaizen_whee_a", "ui_reaction_kaizen_whee_b", "ui_reaction_kaizen_whee_c"],
  ["ui_reaction_kaizen_whee_a", "ui_reaction_kaizen_whee_b", "ui_reaction_kaizen_whee_c"],
  ["ui_reaction_kaizen_whee_a", "ui_reaction_kaizen_whee_b", "ui_reaction_kaizen_whee_c"],
  ["ui_reaction_kaizen_whee_a", "ui_reaction_kaizen_whee_b", "ui_reaction_kaizen_whee_c"],
  ["ui_reaction_kaizen_whee_a", "ui_reaction_kaizen_whee_b", "ui_reaction_kaizen_whee_c"],
  ["ui_reaction_kaizen_whee_a", "ui_reaction_kaizen_whee_b", "ui_reaction_kaizen_whee_c"],
  ["ui_reaction_kaizen_whee_a", "ui_reaction_kaizen_whee_b", "ui_reaction_kaizen_whee_c"],
  ["ui_reaction_kaizen_whee_a", "ui_reaction_kaizen_whee_b", "ui_reaction_kaizen_whee_c"],
  ["ui_reaction_kaizen_whee_a", "ui_reaction_kaizen_whee_b", "ui_reaction_kaizen_whee_c"],
  ["ui_reaction_kaizen_whee_a", "ui_reaction_kaizen_whee_b", "ui_reaction_kaizen_whee_c"],
  ["ui_reaction_kaizen_whee_a", "ui_reaction_kaizen_whee_b", "ui_reaction_kaizen_whee_c"],
  ["ui_reaction_kaizen_whee_a", "ui_reaction_kaizen_whee_b", "ui_reaction_kaizen_whee_c"],
  ["ui_reaction_kaizen_whee_a", "ui_reaction_kaizen_whee_b", "ui_reaction_kaizen_whee_c"],
  ["ui_reaction_kaizen_whee_a", "ui_reaction_kaizen_whee_b", "ui_reaction_kaizen_whee_c"],
  ["ui_reaction_kaizen_whee_a", "ui_reaction_kaizen_whee_b", "ui_reaction_kaizen_whee_c"],
];