export const reaction : Map<string , string> = new Map<string , string>([
  ["ui_reaction_kaizen_amazing_a","This is amazing"],
  ["ui_reaction_kaizen_amazing_b","This is amazing"],
  ["ui_reaction_kaizen_amazing_c","This is amazing"],
  ["ui_reaction_kaizen_best-day_a","This is the best day ever"],
  ["ui_reaction_kaizen_best-day_b","This is the best day ever"],
  ["ui_reaction_kaizen_best-day_c","This is the best day ever"],
  ["ui_reaction_kaizen_boing_a","Boing"],
  ["ui_reaction_kaizen_boing_b","Boiiiing"],
  ["ui_reaction_kaizen_boing_c","Boooiiing"],
  ["ui_reaction_kaizen_brilliant_a","Brilliant"],
  ["ui_reaction_kaizen_brilliant_b","Oh brilliant"],
  ["ui_reaction_kaizen_brilliant_c","Brilliant"],
  ["ui_reaction_kaizen_can-t_believe-it_a","I can't believe it"],
  ["ui_reaction_kaizen_can-t_believe-it_b","I can't believe it"],
  ["ui_reaction_kaizen_can-t_believe-it_c","Oh I can't believe it"],
  ["ui_reaction_kaizen_cool_a","It's so cool"],
  ["ui_reaction_kaizen_cool_b","It's sooo cool"],
  ["ui_reaction_kaizen_cool_c","It's so cool"],
  ["ui_reaction_kaizen_excited_a","I'm so excited"],
  ["ui_reaction_kaizen_excited_b","I'm so excited"],
  ["ui_reaction_kaizen_excited_c","I'm so excited"],
  ["ui_reaction_kaizen_great_a","Great"],
  ["ui_reaction_kaizen_hooray_b","Hooray"],
  ["ui_reaction_kaizen_hop_a","Hop"],
  ["ui_reaction_kaizen_hop_b","Hop"],
  ["ui_reaction_kaizen_hop_c","Hop"],
  ["ui_reaction_kaizen_Incredible_a","This is incredible"],
  ["ui_reaction_kaizen_Incredible_c","This is incredible"],
  ["ui_reaction_kaizen_laugh_a","Hahaha"],
  ["ui_reaction_kaizen_laugh_b","Hahaha"],
  ["ui_reaction_kaizen_laugh_c","Hahaha"],
  ["ui_reaction_kaizen_laugh-d","Hahaha"],
  ["ui_reaction_kaizen_love-it_c","I love it"],
  ["ui_reaction_kaizen_ribbit_a","Ribbit ribbit"],
  ["ui_reaction_kaizen_ribbit_b","Ribbit ribbit"],
  ["ui_reaction_kaizen_ribbit_c","Ribbit ribbit"],
  ["ui_reaction_kaizen_splash_a","Splash"],
  ["ui_reaction_kaizen_splash_b","Splash"],
  ["ui_reaction_kaizen_splash_c","Splash"],
  ["ui_reaction_kaizen_wanna-go-even-higher_c","I want to go even higher"],
  ["ui_reaction_kaizen_whee_a","Wheeeeee"],
  ["ui_reaction_kaizen_whee_b","Wheeeeee"],
  ["ui_reaction_kaizen_whee_c","Wheeeeee"],
  ["ui_reaction_kaizen_woah_a","Woah"],
  ["ui_reaction_kaizen_woah_b","Woah"],
  ["ui_reaction_kaizen_woah_c","Woah"],
  ["ui_reaction_kaizen_wow_a","Wooow"],
  ["ui_reaction_kaizen_wow_b","Wooow"],
  ["ui_reaction_kaizen_wow_c","Wooow"],
  ["ui_reaction_kaizen_yeah_a","Yeah"],
  ["ui_reaction_kaizen_yeah_b","Yeah"],
  ["ui_reaction_kaizen_yeah_c","Yeah"],
]);